#!/usr/bin/python3
#
# Josie Bunnell (josephinebunnell@bennington.edu ; Sky Leilani (skyleilani@bennington.edu)
# 
# 3.26.2019

# import RPi.GPIO as GPIO
# GPIO.setmode(GPIO.BOARD) 

import smbus
bus = smbus.SMBus(1)


DEVICE_ADDRESS = 0x70
CONFIG_REGISTER = 0x21

DIMMING_SET = 0xEF
DISPLAY_SETUP = 0x81
DISPLAY_DATA = 0xF

CONFIG_AND_DISPLAY = [0x21, 0x81]


def configure_LED_display(bus):
  
  config_bytes = [DISPLAY_SETUP, DISPLAY_DATA, DIMMING_SET]
  bus.write_i2c_block_data(DEVICE_ADDRESS, CONFIG_REGISTER, config_bytes)
  print("...")

def main():
  
 configure_LED_display(bus)


main()
