#!/usr/bin/python3
# Josie Bunnell (Josephinebunnell@bennington.edu) ; Sky Leilani (skyleilani@bennington.edu) 
# Date Created : 03.18.2019 
# 

import smbus 
import RPi.GPIO as GPIO 

DEVICE_ADDRESS = 0x48 # The address of the i2c device in hex without the r/w bit 
CONFIG_REGISTER = 0x01
CONVERSION_REGISTER = 0x00 

def configure_adc(my_bus):
  bus = smbus.SMBus(1) # connect to i2C channel 1 and GPIO i2C pins 
  config_bytes = [ 0xC4, 0x83 ] # MSB, LSB in hex 
  bus.write_i2c_block_data(DEVICE_ADDRESS, CONFIG_REGISTER, config_bytes)
  
# get_raw_adc_reading(my_bus) - task 10 - sets address pointer register (DEVICE_ADDRESS)
# Returns : raw ADC reading 
# Param : my_bus - smbus i2c object to write to 

  bus = smbus.SMBus(1)
  raw_reading = bus.read_i2c_block_data(DEVICE_ADDRESS, CONVERSION_REGISTER)
  MSB = raw_reading[0] << 8 
  RAW = MSB + raw_reading[1]
  
  print("Least significant byte is... " 
  print(raw_reading[1])
  
  return raw_reading
  
# convert_raw_reading(reading) - task 11 - takes raw ADC reading and converts to voltage 
# Returns : raw_reading - ADC reading in Volts 
# Param : reading - ADC's raw reading 


def convert_raw_reading(reading):
  
    adc_reading = get_raw_adc_reading(DEVICE_ADDRESS)
     RAW = adc_reading[0] + adc_reading[1]
     
     voltage = 0.000076 * RAW 
     
     print("Voltage reading is... ")
     print(voltage)
     
     return voltage
     
  
  configure_adc(DEVICE_ADDRESS)
  final_read = get_raw_adc_reading(DEVICE_ADDRESS)
  
  convert_raw_reading(final_read)
  
